name: Build and Publish Docker Image

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    if: github.actor != 'github-actions[bot]'
    runs-on: self-hosted
    permissions:
      contents: write   # needed for pushing commits
      packages: write   # for GHCR push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Bump patch version
        id: bump
        run: |
          VERSION=$(grep '^version=' server/gradle.properties | cut -d'=' -f2)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          sed -i "s/^version=.*/version=$NEW_VERSION/" server/gradle.properties
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add server/gradle.properties
          git commit -m "chore: bump patch → $NEW_VERSION"
          git push
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cura-server:${{ env.NEW_VERSION }}
            ghcr.io/${{ github.repository_owner }}/cura-server:dev
